### ISSUE TITLE
Infografía TypeScript - Edwin López Santiago

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Edwin14459#1]
[Infografía TypeScript - Edwin López Santiago.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Edwin14459/files/15227171/Infografia.TypeScript.-.Edwin.Lopez.Santiago.pdf)

**Comment by Nelsy21** [comment]
Calificado conforme a la  rúbrica 
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
